icp_localization:
  initial_pose:
    x: 0.0 
    y: 0.0 
    z: 0.0 
    roll: 0.0  # degrees  
    pitch: 0.0 # degrees
    yaw: 0.0  # degrees
  imu_data_topic: "/thorvald_001/imu_raw" #"/versavis/imu" 
  odometry_data_topic: "/thorvald_001/odometry/base_raw" #"/camera/odom/sample" 
  num_accumulated_range_data: 5
  range_data_topic: "/thorvald_001/velodyne_points" #"/rslidar_points" 
  is_use_odometry: true
  is_provide_odom_frame: true
  gravity_vector_filter_time_constant: 0.01
  fixed_frame: "map"
  min_num_odom_msgs_before_ready: 5

calibration:
  imu_to_range_sensor:
    x: 0.0
    y: 0.0
    z: -0.1
    roll: 0.0
    pitch: 0.0 #3.14159
    yaw: 0.0
  odometry_source_to_range_sensor:
    x: 0.0
    y: 0.0
    z: -1.6
    roll: 0.0
    pitch: 0.0 #3.14159
    yaw: 0.0 
